apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ausg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ausg
    app.kubernetes.io/part-of: ci10t-776-0042-app
  name: devfile-sample-ausg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ausg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ausg
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0042-tenant/ci10t-776-0042-app/devfile-sample-ausg@sha256:59dec530b74ebdbe043794a68de09a5ff0c873516137ca4edc08914e2ab8f253
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
